[package]
name = "protocol-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "2.0",features = [ "extra-traits", "parsing" ]}
proc-macro2 = "1.0"
paste = "1.0"